development:
  adapter: postgresql
  encoding: utf8
  database: friend_food_development
  username: postgres
  password: postgres
  host: localhost

test:
  adapter: postgresql
  encoding: utf8
  database: friend_food_test
  username: postgres
  password: postgres
  host: localhost

production:
  adapter: postgresql
  encoding: utf8
  database: friend_food_production
  username: postgres
  password: postgres
  host: localhost
